# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
